### ISSUE TITLE
[question] how does it improve?

### ISSUE THREAD

**Issue by u007** [cloudposse/varnish#3]
hi,

ive tested a website to point the ip of a domain to my 127.0.0.1 ip, and run it through docker on your docker with port 80:80 mapped and backend ip pointing to the real ip.

after several click and refresh, i did not see any improvement the page load.
what is the purpose of varnish if it doesn't cache entire page?

thanks

**Comment by osterman** [comment]
@u007 unfortunately, there's no silver bullet. This is a general `varnish` docker image that we use on Kubernetes with this `helm` chart: https://github.com/cloudposse/charts/blob/master/incubator/varnish/templates/configmap.yaml

The long and short of it is you need to mount a varnish config into the container that defines the cache rules for your app. Kubernetes makes this very easy to do using `ConfigMaps`. 

This image only provides a light weight varnish docker image. The `helm` chart we provide has some advanced rules that are suitable for Wordpress and a default configuration as well.

**Comment by aknysh** [comment]
@u007  please let us know if the comment above addressed your question.
We'll close the issue for now, let us know if you have other questions or concerns.

**Comment by u007** [comment]
yes thanks
